### ISSUE TITLE
Could not load type 'System.Web.Optimization.BundleModule'.

### ISSUE THREAD

**Issue by nikoletay** [frapid/frapid#30]
Hi, I am trying to install frapid. Followed the install frapid documentation. However, my https://localhost/install is unable to show up. It keeps on having this error: Could not load type 'System.Web.Optimization.BundleModule'.

**Comment by mixerp** [comment]
I assume that you've read the docs and you're familiar with frapid configuration files.

Please try to build first by running build.bat on the root directory. You may need to add nuget commandline in order to build frapid.

Once the build is complete, make sure that "Frapid.Web" is the root directory for IIS. Browse the url "/install" and the installation should continue normally.

**Comment by nikoletay** [comment]
Hi, thanks for your reply.

Are you referring to the all.bat file in the builds folder? I do not see a build.bat file in the root directly. 
As for the nuget commandline, do you mind providing me with the exact line and location where I should add it in, please?

Thank you for your help!

**Comment by SINCOltda** [comment]
Hello nikoletay! have u found a fix for this problem?

**Comment by mixerp** [comment]
If you cannot access `/install` path, you can still create tenant using the frapid command line (frapid.exe):

`create site SiteName provider ProdiverName`

Example:

create site postgresql.localhost provider Npgsql
or
create site sqlserver.localhost provider System.Data.SqlClient
